int main(int argc __attribute__((unused)), char *argv[])
int main(int argc, char __attribute__((__unused__)) *argv[])
int main(int argc, char *argv[])
int main(int argc, char *argv[])
int main(int argc, char *argv[])
